#
# GitHub Actions Workflow for pull request events against main
# check for problems in links.

name: Check links
on:
  pull_request:
    branches: [ main ]

jobs:
  check_links:
    name: Check Markdown links  # TODO: Check also Asciidoc (this should take place in https://github.com/cf-convention/cf-conventions)
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Link Checker
        uses: lycheeverse/lychee-action@v1.5.1
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}

      - name: Upload link report
        uses: actions/upload-artifact@v3
        with:
          name: link-report.md
          path: ./lychee/out.md